### ISSUE TITLE
[Feature]Create Database for the todo list app

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Todo-App#5]

**Comment by deeppss** [comment]
Hello! I would like to work on this issue. Can you pls assign it.

**Comment by Nitesh-thapliyal** [comment]
> Hello! I would like to work on this issue. Could you pls assign it. I'm planning to store all the data on SQLite database.

Go Ahead @deeppss Make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/
